name: Test Terraform

inputs:
  access-key:
    description: Access key used to authenticate
    required: true
  secret-key:
    description: Secret key used to authenticate

runs:
  using: composite
  steps:
    - uses: tlsquared/github-actions/terraform-init@main
      with:
        access-key: ${{ inputs.access-key }}
        secret-key: ${{ inputs.secret-key }}
    - run: terraform validate
      shell: sh
      working-directory: terraform
