name: Lint Python

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v5
    - uses: actions/setup-python@v5
      with:
        python-version-file: .tool-versions
    - run: uv run ruff check
      shell: sh
