name: Build and push image

inputs:
  registry:
    description: Server address of the registry
    required: true
  username:
    description: Username used to log in
    default: nologin
  password:
    description: Password used to log in
    required: true

runs:
  using: composite
  steps:
    - uses: docker/metadata-action@v5
      id: meta
      with:
        images: ${{ inputs.registry }}/image
        tags: type=sha,format=long

    - uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
